# -*- coding: utf-8 -*-
"""Image_Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CjAMgkPZo5rttz32U_PcMjkqJOe8LMVa

***

# DATA PREPROCESSING



1 - RESIZE

2 - FLATTEN
"""

import pandas as pd
import matplotlib.pyplot as plt
import os
import numpy as np
from skimage.io import imread
from skimage.transform import resize

target = []
images = []
flat_data = []

Data_dir = '/content/drive/MyDrive/Colab Notebooks/Python_ML/IMAGES'
Categories = ['CAT','DOG']

for category in Categories:
  class_num = Categories.index(category)
  path = os.path.join(Data_dir,category)
  for img in os.listdir(path):
    img_array = imread(os.path.join(path,img))
    #print(img_array.shape)
    #plt.imshow(img_array)


    img_resize = resize(img_array,(150,150,3))
    flat_data.append(img_resize.flatten())
    images.append(img_resize)
    target.append(class_num)

flat_data = np.array(flat_data)
target = np.array(target)
images = np.array(images)
#from google.colab import drive
#drive.mount('/content/drive')

unique,count = np.unique(target,return_counts=True)
plt.bar(Categories,count)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(flat_data,target,test_size=0.3,random_state=109)

from sklearn.model_selection import GridSearchCV
from sklearn import svm
param_grid = [
    {'C':[1,10,100,1000],'kernel':['linear']},
    {'C':[1,10,100,1000],'gamma':[0.001,0.0001],'kernel':['rbf']},


]
svc = svm.SVC(probability=True)
clf = GridSearchCV(svc,param_grid)
clf.fit(x_train,y_train)

y_pred =clf.predict(x_test)
y_pred

from sklearn.metrics import accuracy_score,confusion_matrix

accuracy_score(y_pred,y_test)

confusion_matrix(y_pred,y_test)

import pickle
pickle.dump(clf,open('img_model.p','wb'))

model = pickle.load(open('img_model.p','rb'))

flat_data = []
url = input("ENTER THE URL OF THE IMAGE : ")
img = imread(url)
img_resized = resize(img,(150,150,3))
flat_data.append(img_resized.flatten())
flat_data=np.array(flat_data)
print(img.shape)
plt.imshow(img_resized)
y_out = model.predict(flat_data)
y_out =Categories[y_out[0]]
print(f' PREDICTION BY THE MODEL : {y_out}')

!pip install streamlit

!pip install pyngrok

#!ngrok update

#!ngrok http 8501

"""# DEPLOYMENT

1 - WEBPAGE

2 - WEBAPP

3- MOBILE APP
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile classification.py
# 
# import streamlit as st
# import numpy as np
# from skimage.io import imread
# from skimage.transform import resize
# import pickle
# from PIL import Image
# st.title("Image Classifier")
# st.text("upload the image")
# 
# model = pickle.load(open('img_model.p','rb'))
# uploadede_file = st.file_uploader("Choose an image. . . .",type="jpg")
# if uploaded_file is not None:
#  img = Image.open(uploaded_file)
#  st.image(img,caption='Uploaded image')
# 
#  if st.button('PREDICT'):
#   Categories = ['CAT','DOG','FISH']
#   st.write('Result. . .')
#   flat_data = []
#  img = np.array(img)
#  img_resized = resize(img,(150,150,3))
#  flat_data.append(img_resized.flatten())
#  flat_data=np.array(flat_data)
#  print(img.shape)
#  plt.imshow(img_resized)
#  y_out = model.predict(flat_data)
#  y_out =Categories[y_out[0]]
#  print(f' PREDICTION BY THE MODEL : {y_out}')
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile class.py
# import streamlit as st
# st.title('IMAGE CLASSIFIER')

!npx install localtunnel --port 8000

!streamlit run class.py &npx localtunnel --port 8501

!nohup streamlit run class.py &

url = ngrok.connect(port="3000")
print(url)

from pyngrok import ngrok

url = ngrok.connect(port=8501)
url

!ngrok http 8501

"""# ROUGH

"""

# Commented out IPython magic to ensure Python compatibility.
!pip install ipython-autotime
# %load_ext autotime

!pip install pyngrok

!pip install -U ipykernel

!pip install -q streamlit

"""./ngrok authtoken XXXXXXXXXXXXXXXX"""

